### ISSUE TITLE
Maybe we should support "ebdb+syncthing" mode

### ISSUE THREAD

**Issue by tumashu** [girzel/ebdb#55] opened 2017-10-14 03:11 UTC
syncthing (https://syncthing.net/) is an open source sync tool, it support android, bsd, window and linux,
I think this is a good tool to let ebdb work with mobile phone, the problem is that: how to merge contact...

**Comment by girzel** [comment] 2017-10-14 12:03
How would you like it to work? As far as I know, you could just put your EBDB file in a synced directory, and different computers could access it. Do mean something different?

If you mean actually syncing EBDB contacts with the contacts app on your phone, that's part of the plan, but it's going to take a while.

**Comment by tumashu** [comment] 2017-10-17 03:14
```
If you mean actually syncing EBDB contacts with the contacts app on your phone, that's part of the plan, but it's going to take a while.
```

Yes

**Comment by girzel** [comment] 2017-10-17 03:31
Okay, that's on the roadmap.

Duplicate of #4

**Closed by girzel** 2017-10-17 03:31 UTC
Labels: enhancement
