### ISSUE TITLE
Google Contacts Sync

### ISSUE THREAD

**Issue by ddoherty03** [girzel/ebdb#36] opened 2017-02-24 14:46 UTC
While everyone is making wishes, here's mine.  Provide two-way sync between ebdb and google contacts.

Having my phone world and desktop world re-united, contacts-wise, would be really nice.

**Comment by girzel** [comment] 2017-02-24 16:28
Hi! I'm not actually sure what mechanism Google Contacts uses for syncing, but I'll do my best to support it. I'm currently working on export/import/database support for Vcard (see #3 ), and once that's done will tackle syncing with various backends, CardDav first (see #4 ).

I have no idea if Google's contacts system speaks CardDav, but if it doesn't I'll do my best to figure out how it works. No promises on timeline, though.

**Comment by ddoherty03** [comment] 2017-02-25 17:13
I currently use org-caldav to get sync my org appointments, etc., with a Nextcloud server that I have running on an AWS server.  My phone syncs to this as well, so I get calendar syncing in two hops, with Nextcloud as the hub in the process.  Nextcloud also has a Contacts app section, so that might work there as well.  Thanks for looking at my aggessive wishes!

**Comment by girzel** [comment] 2017-02-25 18:47
Good! Nextcloud is built on SabreDAV, which speaks CardDAV, and that's
what I'll support when #4 is done. I'm going to close this as a
duplicate of that bug.

**Closed** 2017-02-25 18:49 UTC
Labels: enhancement

**Comment by ddoherty03** [comment] 2017-03-02 09:19
OK.  That would be awesome.
