### ISSUE TITLE
Importing vcard from Android 7.0

### ISSUE THREAD

**Issue by DrWaleedAYousef** [girzel/ebdb#66] opened 2018-05-18 22:56 UTC
I export my contacts from Android 7.0; it seems that it uses vcard 4.0 (not sure). Anyway, EBDB is not able to import from the vcard file! Any help?

Thanks so much.

**Comment by girzel** [comment] 2018-05-18 23:42
Coincidentally, I started working on that just today -- it will be part
of EBDB, but require the parsec package. It might take a me a few weeks
to get it finished, though...

**Comment by girzel** [comment] 2018-05-18 23:44
Duplicate of #2 
Duplicate of #60

**Closed by girzel** 2018-05-18 23:44 UTC
