### ISSUE TITLE
EBDB doesn't show non-ASCII characters correctly

### ISSUE THREAD

**Issue by pietvo** [girzel/ebdb#117] opened 2024-09-13 11:42 UTC
I have a couple of names in my database with non-ASCII characters. However, these show up as the unencoded UTF-8 bytes in the `*EBDB*` buffer and also in the To: field of a message compose buffer.

Fore example `Noël` comes out as `No\303\253l` where the \xxx is one byte, not 4 characters.

Did I miss some setting to have these decoded, so that they look correctly or is this functionality missing from `ebdb`?

**Comment by girzel** [comment] 2024-09-13 17:06
That's weird, EBDB doesn't do anything special with file coding, and relies on `eieio-persistent-save`, and `eieio-persistent-read`. The former uses `(coding-system-for-write 'utf-8-emacs)`, and that's what should be used for the latter, too.
EBDB itself also adds 'utf-8-emacs as an entry for the database files in `auto-coding-alist`, but that should only be relevant if you're visiting the ebdb.dat file in an Emacs buffer (if you visit the file as an Emacs buffer, does the name in question display correctly?).
Otherwise, I guess check the value of `buffer-file-coding-system` in an EBDB buffer. It should be 'utf-8-* but I assume it isn't for you; the trick will be figuring out why.
I have contact with `ë` in their name, and they display just fine...

**Comment by pietvo** [comment] 2024-09-14 08:02
It appears to come from importing from BBDB. I started my EBDB database just by importing it from BBDB. So it seems that this import doesn't use the proper encoding, even though my `.bbdb` file has the encoding line `;; -*-coding: utf-8-emacs;-*-`.

I had tried to manually correct some entries, but maybe I forgot to save them (something that I was used to happen automatically with BBDB). I tried it again and now they are correct.

So maybe I did something wrong while importing from BBDB or maybe there is still a bug there.

**Comment by girzel** [comment] 2024-09-14 16:37
Interesting. Importing just uses `find-file-noselect` on the BBDB file, with the `rawfile` argument left at `nil`, so in theory we're just doing whatever Emacs would do by default. But at least this gives me a potential reproduction case; let me try it and get back to you.

**Comment by girzel** [comment] 2024-09-15 16:09
Just to make sure I'm testing the right thing here, would you give me a sample of the `.bbdb` file you're importing, with just the one contact in it? Something that has the correct BBDB `file-format` and encoding cookie, and the contact with the non-ASCII name. Feel free to remove or anonymize other contact information, of course.

**Comment by pietvo** [comment] 2024-09-16 13:05
Here is a selection. However, while preparing this file I noticed that Emacs would not automatically save the file as `UTF-8,` but wanted to choose `raw-encoding`. It appears there was a stray byte `\240` in the file, which I think is a non-breaking space, but not UTF-8 encoded. So it could be that this byte made emacs not choose the `UTF-8` encoding while opening the file , notwithstanding the `-*-coding: utf-8-emacs;-*-` line.

[BBDB.txt](https://github.com/user-attachments/files/17013554/BBDB.txt)

**Comment by girzel** [comment] 2024-09-16 17:32
Yes, I can confirm that with `emacs -Q` and the attached file, the imported contacts have properly-encoded names, and everything displays correctly. I expect the stray byte was the cause of the issue.

**Comment by girzel** [comment] 2024-09-19 14:32
I'm closing this issue, feel free to re-open if it turns out there's something else going on here.

**Closed as completed by girzel** 2024-09-19 14:32 UTC
